Repository UB-ES-2020-A/Scribd, pull requests merged in 2020-12, with the labels that each got.

#212 Tech debt 4 2 consistent endpoint styling
  Scribd/urls.py
  Scribd/views.py
  templates/scribd/base.html
Labels: FE

#213 Added new files pages
  Scribd/static/css/modern-business.css
  Scribd/static/js/contact_me.js
  Scribd/static/js/jqBootstrapValidation.js
  Scribd/static/mail/contact_me.php
  Scribd/static/vendor/bootstrap/css/bootstrap-grid.css
  Scribd/static/vendor/bootstrap/css/bootstrap-grid.css.map
  Scribd/static/vendor/bootstrap/css/bootstrap-grid.min.css
  Scribd/static/vendor/bootstrap/css/bootstrap-grid.min.css.map
  Scribd/static/vendor/bootstrap/css/bootstrap-reboot.css
  Scribd/static/vendor/bootstrap/css/bootstrap-reboot.css.map
  Scribd/static/vendor/bootstrap/css/bootstrap-reboot.min.css
  Scribd/static/vendor/bootstrap/css/bootstrap-reboot.min.css.map
  Scribd/static/vendor/bootstrap/css/bootstrap.css
  Scribd/static/vendor/bootstrap/css/bootstrap.css.map
  Scribd/static/vendor/bootstrap/css/bootstrap.min.css
  Scribd/static/vendor/bootstrap/css/bootstrap.min.css.map
  Scribd/static/vendor/bootstrap/js/bootstrap.bundle.js
  Scribd/static/vendor/bootstrap/js/bootstrap.bundle.js.map
  Scribd/static/vendor/bootstrap/js/bootstrap.bundle.min.js
  Scribd/static/vendor/bootstrap/js/bootstrap.bundle.min.js.map
  Scribd/static/vendor/bootstrap/js/bootstrap.js
  Scribd/static/vendor/bootstrap/js/bootstrap.js.map
  Scribd/static/vendor/bootstrap/js/bootstrap.min.js
  Scribd/static/vendor/bootstrap/js/bootstrap.min.js.map
  Scribd/static/vendor/jquery/jquery.js
  Scribd/static/vendor/jquery/jquery.min.js
  Scribd/static/vendor/jquery/jquery.min.map
  Scribd/static/vendor/jquery/jquery.slim.js
  Scribd/static/vendor/jquery/jquery.slim.min.js
  Scribd/static/vendor/jquery/jquery.slim.min.map
  requirements.txt
  templates/new_page/404.html
  templates/new_page/about.html
  templates/new_page/blog-home-1.html
  templates/new_page/blog-home-2.html
  templates/new_page/blog-post.html
  templates/new_page/contact.html
  templates/new_page/faq.html
  templates/new_page/full-width.html
  templates/new_page/gulpfile.js
  templates/new_page/index.html
  templates/new_page/package-lock.json
  templates/new_page/package.json
  templates/new_page/portfolio-1-col.html
  templates/new_page/portfolio-2-col.html
  templates/new_page/portfolio-3-col.html
  templates/new_page/portfolio-4-col.html
  templates/new_page/portfolio-item.html
  templates/new_page/pricing.html
  templates/new_page/services.html
  templates/new_page/sidebar.html
  templates/scribd/base.html
Labels: FE

#214 refactoring
  .travis.yml
  Scribd/test_views.py
  Scribd/views.py
  ScribdProject/urls.py
  templates/forms/add_book.html
  templates/forms/cancel_suscription_confirmation.html
  templates/forms/edit_provider_profile.html
  templates/forms/edit_user_profile.html
  templates/forms/update_payment.html
  templates/forms/upgrade_account.html
  templates/forms/upload.html
  templates/registration/login.html
  templates/registration/signup.html
  templates/scribd-deprecated/base.html
  templates/scribd-deprecated/contract.html
  templates/scribd-deprecated/ebook_change.html
  templates/scribd-deprecated/ebook_detail.html
  templates/scribd-deprecated/mainpage.html
  templates/scribd-deprecated/providers_homepage.html
  templates/scribd-deprecated/review.html
  templates/scribd-deprecated/support_page.html
  templates/scribd-deprecated/ticketdetail.html
  templates/scribd-deprecated/tickets.html
  templates/scribd-deprecated/user_profile_page.html
  templates/scribd/404.html
  templates/scribd/about.html
  templates/scribd/base.html
  templates/scribd/blog-home-1.html
  templates/scribd/blog-home-2.html
  templates/scribd/blog-post.html
  templates/scribd/contact.html
  templates/scribd/faq.html
  templates/scribd/full-width.html
  templates/scribd/gulpfile.js
  templates/scribd/index.html
  templates/scribd/package-lock.json
  templates/scribd/package.json
  templates/scribd/portfolio-1-col.html
  templates/scribd/portfolio-2-col.html
  templates/scribd/portfolio-3-col.html
  templates/scribd/portfolio-4-col.html
  templates/scribd/portfolio-item.html
  templates/scribd/pricing.html
  templates/scribd/services.html
  templates/scribd/sidebar.html
Labels: FE

#216 fix mainpage
  Scribd/admin.py
  Scribd/context_processors.py
  Scribd/decorators.py
  Scribd/forms.py
  Scribd/models.py
  Scribd/serializers.py
  Scribd/static/css/modern-business.css
  Scribd/static/js/contact_me.js
  Scribd/static/js/jqBootstrapValidation.js
  Scribd/static/vendor/bootstrap/css/bootstrap-grid.css
  Scribd/static/vendor/bootstrap/css/bootstrap-grid.css.map
  Scribd/static/vendor/bootstrap/css/bootstrap-grid.min.css.map
  Scribd/static/vendor/bootstrap/css/bootstrap-reboot.css
  Scribd/static/vendor/bootstrap/css/bootstrap-reboot.css.map
  Scribd/static/vendor/bootstrap/css/bootstrap-reboot.min.css.map
  Scribd/static/vendor/bootstrap/css/bootstrap.css
  Scribd/static/vendor/bootstrap/css/bootstrap.css.map
  Scribd/static/vendor/bootstrap/css/bootstrap.min.css.map
  Scribd/static/vendor/bootstrap/js/bootstrap.bundle.js
  Scribd/static/vendor/bootstrap/js/bootstrap.bundle.js.map
  Scribd/static/vendor/bootstrap/js/bootstrap.bundle.min.js.map
  Scribd/static/vendor/bootstrap/js/bootstrap.js
  Scribd/static/vendor/bootstrap/js/bootstrap.js.map
  Scribd/static/vendor/bootstrap/js/bootstrap.min.js.map
  Scribd/static/vendor/jquery/jquery.js
  Scribd/static/vendor/jquery/jquery.min.map
  Scribd/static/vendor/jquery/jquery.slim.js
  Scribd/static/vendor/jquery/jquery.slim.min.map
  Scribd/test_views.py
  Scribd/urls.py
  Scribd/views.py
  ScribdProject/urls.py
  fixtures/ebooks.json
  templates/forms/update_payment.html
  templates/scribd-deprecated/ebook_detail.html
  templates/scribd-deprecated/support_page.html
  templates/scribd-deprecated/ticketdetail.html
  templates/scribd-deprecated/tickets.html
  templates/scribd/404.html
  templates/scribd/about.html
  templates/scribd/base.html
  templates/scribd/blog-home-1.html
  templates/scribd/blog-home-2.html
  templates/scribd/blog-post.html
  templates/scribd/contact.html
  templates/scribd/faq.html
  templates/scribd/full-width.html
  templates/scribd/gulpfile.js
  templates/scribd/mainpage.html
  templates/scribd/package.json
  templates/scribd/portfolio-1-col.html
  templates/scribd/portfolio-2-col.html
  templates/scribd/portfolio-3-col.html
  templates/scribd/portfolio-4-col.html
  templates/scribd/portfolio-item.html
  templates/scribd/pricing.html
  templates/scribd/services.html
  templates/scribd/sidebar.html
Labels: FE

#226 Tech debt 5 1 main page rework
  Scribd/static/images/Cabecera-ESDLA-El-Retorno-del-Rey.jpg
  Scribd/static/images/Cabecera-ESDLA-La-Comunidad-del-Anillo.jpg
  Scribd/static/images/Cabecera-ESDLA-Las-Dos-Torres.jpg
  Scribd/static/images/señor_de_los_anillos_las_dos_torres.jpg
  Scribd/views.py
  media/images/Q.jpeg
  media/images/Q_ZUBinIj.jpeg
  media/images/Q_t9uMUC6.jpeg
  media/images/señor_de_los_anillos_las_dos_torres.jpg
  templates/scribd/mainpage.html
Labels: FE

#229 Tech debt 5 2 profilepage
  Scribd/forms.py
  Scribd/models.py
  Scribd/static/css/user_profile_stylesheet.css
  Scribd/static/images/clouds.jpg
  Scribd/static/images/pencil.png
  Scribd/static/images/portada.jpeg
  Scribd/static/images/portadascribd.png
  Scribd/static/images/scribdLogoinverted.png
  Scribd/static/images/unknown.png
  Scribd/static/readable_content/hp3.pdf
  Scribd/user_models.py
  Scribd/views.py
  media/images/1081458.jpg
  media/images/1081458_276fmcg.jpg
  media/images/1081458_GGGcRvX.jpg
  media/images/1081458_wzmAIb8.jpg
  media/images/775eb5a9d6ac3cce2344b5dbfb2941e5.png
  media/images/775eb5a9d6ac3cce2344b5dbfb2941e5_1WnXfmZ.png
  media/images/775eb5a9d6ac3cce2344b5dbfb2941e5_Z0G3ceb.png
  media/images/775eb5a9d6ac3cce2344b5dbfb2941e5_cFQ1w8a.png
  media/images/8f981a87-f3d9-4d48-b33b-5aca8ac2d228.JPG
  media/images/clouds.jpg
  media/images/clouds_dvrLs59.jpg
  media/images/cuadrados.jpg
  media/images/portadascribd.png
  media/uploads/Etica_LaurentiuNedelcu_OscarJimenez_JoaquimYuste_MarcosPlaza.pdf
  templates/scribd-deprecated/mainpage.html
  templates/scribd-deprecated/user_profile_page.html
  templates/scribd/base.html
  templates/scribd/user_profile_page.html
Labels: FE

#231 Tech debt 5 4 base content
  Scribd/static/images/Q_2.png
  Scribd/static/images/las_dos_torres_.png
  Scribd/urls.py
  Scribd/views.py
  ScribdProject/urls.py
  media/images/Q_2.png
  media/images/Q_2_ZCRlH0t.png
  media/images/las_dos_torres_.png
  templates/scribd/base.html
  templates/scribd/ebook_details.html
  templates/scribd/mainpage.html
Labels: FE

#232 Cancel subscription page completed
  Scribd/views.py
  media/uploads/Etica_LaurentiuNedelcu_OscarJimenez_JoaquimYuste_MarcosPlaza_jJkiMHr.pdf
  templates/forms/cancel_subscription_confirmation_v2.html
Labels: FE

#234 Cancel subscription page completed v2 - merge correctly into Frontend
  templates/scribd-deprecated/user_profile_page.html
Labels: FE

#236 Tech debt 5 7 edituserprofilepage
  Scribd/forms.py
  Scribd/static/css/user_profile_stylesheet.css
  media/images/1081458_P36PQ3C.jpg
  media/images/775eb5a9d6ac3cce2344b5dbfb2941e5_Z0G3ceb_0VgvBgq.png
  media/images/8f981a87-f3d9-4d48-b33b-5aca8ac2d228_sV8dW2P.JPG
  media/images/8f981a87-f3d9-4d48-b33b-5aca8ac2d228_sV8dW2P_oAQxhpb.JPG
  media/images/8f981a87-f3d9-4d48-b33b-5aca8ac2d228_sV8dW2P_oAQxhpb_rauIG4b.JPG
  media/images/983794168.jpg
  media/images/Lets_Go_Pikachu_Eevee_Red.webp
  media/images/Lets_Go_Pikachu_Eevee_Red_FY5BpwI.webp
  media/images/cuadrados_aKUedLz.jpg
  media/images/original.jpg
  templates/forms/edit_user_profile_v2.html
  templates/scribd/user_profile_page.html
Labels: FE

#241 Tech debt 5 13 providers contract rework
  templates/scribd/providers_homepage.html
Labels: FE

#246 DRAG AND DROP IS WORKING
  Scribd/forms.py
  Scribd/models.py
  Scribd/static/css/shop-item.css
  Scribd/static/css/styles-upload.css
  Scribd/static/js/upload.js
  Scribd/views.py
  templates/forms/cancel_subscription_confirmation_v2.html
  templates/forms/edit_user_profile_v2.html
  templates/forms/upload.html
  templates/scribd-deprecated/base.html
  templates/scribd/ebook_details.html
  templates/scribd/forumdetail.html
  templates/scribd/mainpage.html
  templates/scribd/providers_homepage.html
  templates/scribd/support_page.html
  templates/scribd/ticketdetail.html
Labels: FE

#249 Bugs 2 display images in followed resources
  Scribd/admin.py
  Scribd/views.py
  templates/forms/upload.html
  templates/scribd/ebook_details.html
  templates/scribd/user_profile_page.html
Labels: FE, bug

#251 fix endif
  templates/scribd/user_profile_page.html
Labels: FE, bug

#257 Tech debt 5 12 providers add book rework
  Scribd/forms.py
  Scribd/models.py
  Scribd/views.py
  cypress.json
  media/images/SACdA.jpeg
  templates/forms/upload.html
  templates/scribd/base.html
  templates/scribd/providers_homepage.html
Labels: FE

#262 Tech debt 6 testing
  Scribd/admin.py
  Scribd/apps.py
  Scribd/context_processors.py
  Scribd/decorators.py
  Scribd/forms.py
  Scribd/models.py
  Scribd/permissions.py
  Scribd/serializers.py
  Scribd/test_views.py
  Scribd/tests.py
  Scribd/urls.py
  Scribd/user_models.py
  Scribd/views.py
  ScribdProject/asgi.py
  ScribdProject/jinja2.py
  ScribdProject/settings.py
  ScribdProject/urls.py
  ScribdProject/wsgi.py
  cypress.json
  manage.py
  media/images/wallpaper.jpg
  media/uploads/Creative_user_profile.html
  templates/forms/upload.html
  templates/registration/signup.html
  templates/scribd/base.html
  templates/scribd/ebook_details.html
  templates/scribd/forumdetail.html
  templates/scribd/mainpage.html
  templates/scribd/providers_homepage.html
  templates/scribd/support_page.html
  templates/scribd/ticketdetail.html
  templates/scribd/user_profile_page.html
Labels: Test, bug

#267 Develop
  Scribd/urls.py
  templates/scribd/base.html
  templates/scribd/mainpage.html
  templates/scribd/user_profile_page.html
Labels: API, BBDD, BE, CI, Deployment, DevOps, FE, Refactoring, Rework, Test, bug
