Repository UB-ES-2020-A/Scribd, pull requests merged in 2020-11, with the labels that each got.

#89 Change travis mode with jobs&stages and first test with model ebook
  .travis.yml
  Scribd/tests.py
Labels: Test

#90 Change to staging and production server
  .travis.yml
Labels: DevOps, Test

#91 Change travis Ci and Heroku servers
  .travis.yml
  Scribd/tests.py
Labels: DevOps, Test

#92 Fix admin email & first test
  Scribd/tests.py
  Scribd/user_model.py
Labels: bug

#94 Delete tag on test & automatize tag on release
  .travis.yml
Labels: CI, DevOps, bug

#96 delete tag on heroku and develop staging provider
  .travis.yml
Labels: CI, Deployment, DevOps

#105 fix permissions
  Scribd/migrations/0001_initial.py
  Scribd/migrations/0002_auto_20201031_1808.py
  Scribd/permissions.py
  Scribd/views.py
  ScribdProject/settings.py
  requirements.txt
Labels: API, FE

#116 Modified Model & Api Update Book
  .travis.yml
  Scribd/admin.py
  Scribd/context_processors.py
  Scribd/forms.py
  Scribd/models.py
  Scribd/permissions.py
  Scribd/serializers.py
  Scribd/tests.py
  Scribd/urls.py
  Scribd/user_model.py
  Scribd/views.py
  ScribdProject/urls.py
  templates/forms/add_book.html
  templates/registration/signup.html
  templates/scribd/base.html
  templates/scribd/mainpage.html
  templates/scribd/providers_homepage.html
Labels: API, BBDD, bug

#119 Provider, Supporters and Admin can modify book properties
  Scribd/permissions.py
  Scribd/static/ebooks/el-dia-que-se-perdio-la-cordura.pdf
  Scribd/static/ebooks/unknown.pdf
  Scribd/urls.py
  Scribd/views.py
  ScribdProject/settings.py
Labels: API, BBDD, BE, FE, bug

#120 P_3_3 change atributes of book
  Scribd/views.py
Labels: API, FE

#121 First Release tomorrow
  .travis.yml
  Scribd/admin.py
  Scribd/context_processors.py
  Scribd/forms.py
  Scribd/migrations/0001_initial.py
  Scribd/migrations/0002_auto_20201031_1808.py
  Scribd/models.py
  Scribd/permissions.py
  Scribd/serializers.py
  Scribd/static/ebooks/el-dia-que-se-perdio-la-cordura.pdf
  Scribd/static/ebooks/unknown.pdf
  Scribd/test_views.py
  Scribd/tests.py
  Scribd/urls.py
  Scribd/user_model.py
  Scribd/views.py
  ScribdProject/settings.py
  ScribdProject/urls.py
  fixtures/ebooks.json
  requirements.txt
  templates/forms/add_book.html
  templates/registration/signup.html
  templates/scribd/base.html
  templates/scribd/ebook_change.html
  templates/scribd/mainpage.html
  templates/scribd/providers_homepage.html
  templates/scribd/support_page.html
  templates/scribd/tickets.html
Labels: Deployment

#138 Develop
  .gitignore
  Scribd/forms.py
  Scribd/models.py
  Scribd/serializers.py
  Scribd/tests.py
  Scribd/urls.py
  Scribd/user_model.py
  Scribd/views.py
  ScribdProject/settings.py
  ScribdProject/urls.py
  fixtures/ebooks.json
  media/ebooks/el-dia-que-se-perdio-la-cordura.pdf
  media/ebooks/unknown.pdf
  media/images/HP3.jpg
  media/images/SACdA.jpg
  media/images/eldiaqueseperdiolacordura.jpg
  media/images/unknown.png
  renew_local_db.sh
  requirements.txt
  templates/forms/edit_provider_profile.html
  templates/forms/edit_user_profile.html
  templates/forms/upgrade_account.html
  templates/forms/upload.html
  templates/registration/signup.html
  templates/scribd/base.html
  templates/scribd/contract.html
  templates/scribd/ebooks_list.html
  templates/scribd/mainpage.html
  templates/scribd/providers_homepage.html
  templates/scribd/support_page.html
  templates/scribd/user_profile_page.html
Labels: Deployment

#180 Tech debt 1 1 refactoring all users models
  .gitignore
  Scribd/admin.py
  Scribd/forms.py
  Scribd/models.py
  Scribd/permissions.py
  Scribd/serializers.py
  Scribd/tests.py
  Scribd/urls.py
  Scribd/user_model.py
  Scribd/user_models.py
  Scribd/views.py
  ScribdProject/settings.py
  ScribdProject/urls.py
  renew_local_db.sh
  templates/registration/signup.html
  templates/scribd/ebook_detail.html
  templates/scribd/user_profile_page.html
Labels: Refactoring

#181 [users_4_1] Search for different types of books by Category
  Scribd/forms.py
  Scribd/models.py
  Scribd/tests.py
  Scribd/urls.py
  Scribd/views.py
  templates/scribd/base.html
  templates/scribd/ebooks_list.html
  templates/scribd/mainpage.html
Labels: FE

#184 fix bug urls
  Scribd/views.py
Labels: FE

#185 Multisearching working
  Scribd/models.py
  Scribd/views.py
  templates/scribd/base.html
  templates/scribd/mainpage.html
Labels: FE

#187 prova travis
  .gitignore
  README.md
  Scribd/admin.py
  Scribd/forms.py
  Scribd/models.py
  Scribd/permissions.py
  Scribd/serializers.py
  Scribd/tests.py
  Scribd/urls.py
  Scribd/user_model.py
  Scribd/user_models.py
  Scribd/views.py
  ScribdProject/settings.py
  ScribdProject/urls.py
  renew_local_db.sh
  requirements.txt
  templates/registration/signup.html
  templates/scribd/base.html
  templates/scribd/ebook_detail.html
  templates/scribd/ebooks_list.html
  templates/scribd/mainpage.html
  templates/scribd/user_profile_page.html
Labels: Deployment

#188 reviews
  Scribd/forms.py
  Scribd/models.py
  Scribd/urls.py
  Scribd/views.py
  templates/scribd/ebook_detail.html
  templates/scribd/review.html
Labels: BBDD, BE

#189 Users 1 1
  Scribd/forms.py
  Scribd/tests.py
  Scribd/user_models.py
  Scribd/views.py
  fixtures/ebooks.json
  templates/forms/upgrade_account.html
  templates/registration/signup.html
  templates/scribd/ebook_detail.html
  templates/scribd/mainpage.html
  templates/scribd/user_profile_page.html
Labels: API, BBDD, BE, FE

#190 Button added close #158
  Scribd/views.py
  templates/scribd/user_profile_page.html
Labels: FE

#191 Cancel subscription done
  Scribd/forms.py
  Scribd/urls.py
  Scribd/views.py
  templates/forms/cancel_suscription_confirmation.html
  templates/scribd/ebook_detail.html
  templates/scribd/user_profile_page.html
Labels: BE, FE

#192 We can read the file (change the href at the final moment)
  Scribd/models.py
  Scribd/urls.py
  Scribd/views.py
  templates/scribd/ebook_detail.html
  templates/scribd/pdf_reader.html
  templates/scribd/user_profile_page.html
Labels: FE, enhancement

#193 We can navigate through scrolling (only locally at the moment)
  templates/scribd/pdf_reader.html
Labels: FE, enhancement

#194 Su 8 2 frontend recomendators
  Scribd/urls.py
  Scribd/views.py
  templates/scribd/ebook_detail.html
  templates/scribd/review.html
Labels: FE

#196 endpoints protected (almost all)
  Scribd/decorators.py
  Scribd/urls.py
  Scribd/views.py
  templates/scribd/support_page.html
Labels: BE

#197 User can download the file
  templates/forms/upgrade_account.html
Labels: FE, enhancement

#200 Final commit SPRINT 3
  Scribd/admin.py
  Scribd/context_processors.py
  Scribd/decorators.py
  Scribd/forms.py
  Scribd/models.py
  Scribd/serializers.py
  Scribd/test_views.py
  Scribd/urls.py
  Scribd/user_models.py
  Scribd/views.py
  ScribdProject/settings.py
  ScribdProject/urls.py
  fixtures/ebooks.json
  templates/forms/cancel_suscription_confirmation.html
  templates/forms/update_payment.html
  templates/forms/upgrade_account.html
  templates/registration/signup.html
  templates/scribd/ebook_detail.html
  templates/scribd/mainpage.html
  templates/scribd/review.html
  templates/scribd/support_page.html
  templates/scribd/ticketdetail.html
  templates/scribd/tickets.html
  templates/scribd/user_profile_page.html
Labels: Deployment
